DEF HIDE EQU $11
DEF SHOW EQU $15

; MissableObjects indexes (see data/maps/hide_show_data.asm)
; this is a list of the sprites that can be enabled/disabled during the game
; TODO: mark sprite constants with an X that are never used

	const_def
	const HS_PALLET_TOWN_OAK               ; 00
	const HS_PALLET_TOWN_PIKATWO           ; 01
	const HS_PALLET_TOWN_CRAMORANT         ; 02
	const HS_LYING_OLD_MAN                 ; 03
	const HS_OLD_MAN_1                     ; 04
	const HS_OLD_MAN                       ; 05
	const HS_MUSEUM_GUY                    ; 06
	const HS_GYM_GUY                       ; 07
	const HS_CERULEAN_RIVAL                ; 08
	const HS_CERULEAN_ROCKET               ; 09
	const HS_CERULEAN_GUARD_1              ; 0A
	const HS_CERULEAN_CAVE_GUY             ; 0B
	const HS_CERULEAN_GUARD_2              ; 0C
	const HS_CELADON_CITY_TM_GUY		   ; 0D
	const HS_SAFFRON_CITY_1                ; 0E
	const HS_SAFFRON_CITY_2                ; 0F
	const HS_SAFFRON_CITY_3                ; 10
	const HS_SAFFRON_CITY_4                ; 11
	const HS_SAFFRON_CITY_5                ; 12
	const HS_SAFFRON_CITY_6                ; 13
	const HS_SAFFRON_CITY_7                ; 14
	const HS_SAFFRON_CITY_8                ; 15
	const HS_SAFFRON_CITY_9                ; 16
	const HS_SAFFRON_CITY_A                ; 17
	const HS_SAFFRON_CITY_B                ; 18
	const HS_SAFFRON_CITY_C                ; 19
	const HS_SAFFRON_CITY_D                ; 1A
	const HS_SAFFRON_CITY_E                ; 1B
	const HS_SAFFRON_CITY_F                ; 1C
	const HS_ROUTE_2_ITEM_1                ; 1D
	const HS_ROUTE_2_ITEM_2                ; 1E
	const HS_ROUTE_4_ITEM                  ; 1F
	const HS_ROUTE_9_ITEM                  ; 20
	const HS_ROUTE_12_SNORLAX              ; 21
	const HS_ROUTE_12_ITEM_1               ; 22
	const HS_ROUTE_12_ITEM_2               ; 23
	const HS_ROUTE_15_ITEM                 ; 24
	const HS_ROUTE_16_SNORLAX              ; 25
	const HS_ROUTE_22_RIVAL_1              ; 26
	const HS_ROUTE_22_RIVAL_2              ; 27
	const HS_NUGGET_BRIDGE_GUY             ; 28
	const HS_ROUTE_24_ITEM                 ; 29
	const HS_ROUTE_25_ITEM                 ; 2A
	const HS_REDS_HOUSE_2F_CRAM_PLUSH
	const HS_REDS_HOUSE_2F_TROPHY
	const HS_DAISY_SITTING                 ; 2B
	const HS_DAISY_WALKING                 ; 2C
	const HS_TOWN_MAP                      ; 2D
	const HS_OAKS_LAB_RIVAL                ; 2E
	const HS_STARTER_BALL_1                ; 2F
	const HS_OAKS_LAB_OAK_1                ; 30
	const HS_POKEDEX_1                     ; 31
	const HS_POKEDEX_2                     ; 32
	const HS_OAKS_LAB_OAK_2                ; 33
	const HS_VIRIDIAN_GYM_GIOVANNI         ; 34
	const HS_VIRIDIAN_GYM_ITEM             ; 35
	const HS_OLD_AMBER                     ; 36
	const HS_CERULEAN_BULBASAUR            ; 37
	const HS_CERULEAN_CAVE_1F_ITEM_1       ; 38
	const HS_CERULEAN_CAVE_1F_ITEM_2       ; 39
	const HS_CERULEAN_CAVE_1F_ITEM_3       ; 3A
	const HS_CERULEAN_CAVE_1F_ITEM_4       ; 3B
	const HS_POKEMON_TOWER_2F_RIVAL        ; 3C
	const HS_POKEMON_TOWER_3F_ITEM         ; 3D
	const HS_POKEMON_TOWER_4F_ITEM_1       ; 3E
	const HS_POKEMON_TOWER_4F_ITEM_2       ; 3F
	const HS_POKEMON_TOWER_4F_ITEM_3       ; 40
	const HS_POKEMON_TOWER_5F_ITEM         ; 41
	const HS_POKEMON_TOWER_6F_ITEM_1       ; 42
	const HS_POKEMON_TOWER_6F_ITEM_2       ; 43
	const HS_POKEMON_TOWER_7F_JESSIE       ; 44
	const HS_POKEMON_TOWER_7F_JAMES        ; 45
	const HS_POKEMON_TOWER_7F_MR_FUJI      ; 46
	const HS_MR_FUJIS_HOUSE_MR_FUJI        ; 47
	const HS_CELADON_MANSION_2F_ME1
	const HS_CELADON_MANSION_2F_ME2
	const HS_CELADON_MANSION_EEVEE_GIFT    ; 48
	const HS_GAME_CORNER_ROCKET            ; 49
	const HS_WARDENS_HOUSE_ITEM            ; 4A
	const HS_POKEMON_MANSION_1F_ITEM_1     ; 4B
	const HS_POKEMON_MANSION_1F_ITEM_2     ; 4C
	const HS_FIGHTING_DOJO_GIFT_1          ; 4D
	const HS_FIGHTING_DOJO_GIFT_2          ; 4E
	const HS_SILPH_CO_1F_RECEPTIONIST      ; 4F
	const HS_VOLTORB_1                     ; 50
	const HS_VOLTORB_2                     ; 51
	const HS_VOLTORB_3                     ; 52
	const HS_ELECTRODE_1                   ; 53
	const HS_VOLTORB_4                     ; 54
	const HS_VOLTORB_5                     ; 55
	const HS_ELECTRODE_2                   ; 56
	const HS_VOLTORB_6                     ; 57
	const HS_ZAPDOS                        ; 58
	const HS_POWER_PLANT_ITEM_1            ; 59
	const HS_POWER_PLANT_ITEM_2            ; 5A
	const HS_POWER_PLANT_ITEM_3            ; 5B
	const HS_POWER_PLANT_ITEM_4            ; 5C
	const HS_POWER_PLANT_ITEM_5            ; 5D
	const HS_MOLTRES                       ; 5E
	const HS_VICTORY_ROAD_2F_ITEM_1        ; 5F
	const HS_VICTORY_ROAD_2F_ITEM_2        ; 60
	const HS_VICTORY_ROAD_2F_ITEM_3        ; 61
	const HS_VICTORY_ROAD_2F_ITEM_4        ; 62
	const HS_VICTORY_ROAD_2F_BOULDER       ; 63
	const HS_BILL_POKEMON                  ; 64
	const HS_BILL_1                        ; 65
	const HS_BILL_2                        ; 66
	const HS_VIRIDIAN_FOREST_ITEM_1        ; 67
	const HS_VIRIDIAN_FOREST_ITEM_2        ; 68
	const HS_VIRIDIAN_FOREST_ITEM_3        ; 69
	const HS_MT_MOON_1F_ITEM_1             ; 6A
	const HS_MT_MOON_1F_ITEM_2             ; 6B
	const HS_MT_MOON_1F_ITEM_3             ; 6C
	const HS_MT_MOON_1F_ITEM_4             ; 6D
	const HS_MT_MOON_1F_ITEM_5             ; 6E
	const HS_MT_MOON_1F_ITEM_6             ; 6F
	const HS_MT_MOON_B2F_JESSIE            ; 70
	const HS_MT_MOON_B2F_JAMES             ; 71
	const HS_MT_MOON_B2F_FOSSIL_1          ; 72
	const HS_MT_MOON_B2F_FOSSIL_2          ; 73
	const HS_MT_MOON_B2F_ITEM_1            ; 74
	const HS_MT_MOON_B2F_ITEM_2            ; 75
	const HS_MEW						   ; 76
	const HS_SS_ANNE_2F_RIVAL              ; 77
	const HS_SS_ANNE_1F_ROOMS_ITEM         ; 78
	const HS_SS_ANNE_2F_ROOMS_ITEM_1       ; 79
	const HS_SS_ANNE_2F_ROOMS_ITEM_2       ; 7A
	const HS_SS_ANNE_B1F_ROOMS_ITEM_1      ; 7B
	const HS_SS_ANNE_B1F_ROOMS_ITEM_2      ; 7C
	const HS_SS_ANNE_B1F_ROOMS_ITEM_3      ; 7D
	const HS_VICTORY_ROAD_3F_ITEM_1        ; 7E
	const HS_VICTORY_ROAD_3F_ITEM_2        ; 7F
	const HS_VICTORY_ROAD_3F_BOULDER       ; 80
	const HS_ROCKET_HIDEOUT_B1F_ITEM_1     ; 81
	const HS_ROCKET_HIDEOUT_B1F_ITEM_2     ; 82
	const HS_ROCKET_HIDEOUT_B2F_ITEM_1     ; 83
	const HS_ROCKET_HIDEOUT_B2F_ITEM_2     ; 84
	const HS_ROCKET_HIDEOUT_B2F_ITEM_3     ; 85
	const HS_ROCKET_HIDEOUT_B2F_ITEM_4     ; 86
	const HS_ROCKET_HIDEOUT_B3F_ITEM_1     ; 87
	const HS_ROCKET_HIDEOUT_B3F_ITEM_2     ; 88
	const HS_ROCKET_HIDEOUT_B4F_GIOVANNI   ; 89
	const HS_ROCKET_HIDEOUT_B4F_JAMES      ; 8A
	const HS_ROCKET_HIDEOUT_B4F_JESSIE     ; 8B
	const HS_ROCKET_HIDEOUT_B4F_ITEM_1     ; 8C
	const HS_ROCKET_HIDEOUT_B4F_ITEM_2     ; 8D 
	const HS_ROCKET_HIDEOUT_B4F_ITEM_3     ; 8E
	const HS_ROCKET_HIDEOUT_B4F_ITEM_4     ; 8F 
	const HS_ROCKET_HIDEOUT_B4F_ITEM_5     ; 90
	const HS_SILPH_CO_2F_1                 ; 91 XXX never (de)activated?
	const HS_SILPH_CO_2F_2                 ; 92
	const HS_SILPH_CO_2F_3                 ; 93
	const HS_SILPH_CO_2F_4                 ; 94
	const HS_SILPH_CO_2F_5                 ; 95
	const HS_SILPH_CO_3F_1                 ; 96
	const HS_SILPH_CO_3F_2                 ; 97
	const HS_SILPH_CO_3F_ITEM              ; 98
	const HS_SILPH_CO_4F_1                 ; 99
	const HS_SILPH_CO_4F_2                 ; 9A
	const HS_SILPH_CO_4F_3                 ; 9B
	const HS_SILPH_CO_4F_ITEM_1            ; 9C
	const HS_SILPH_CO_4F_ITEM_2            ; 9D
	const HS_SILPH_CO_4F_ITEM_3            ; 9E
	const HS_SILPH_CO_5F_1                 ; 9F
	const HS_SILPH_CO_5F_2                 ; A0
	const HS_SILPH_CO_5F_3                 ; A1
	const HS_SILPH_CO_5F_4                 ; A2
	const HS_SILPH_CO_5F_ITEM_1            ; A3
	const HS_SILPH_CO_5F_ITEM_2            ; A4
	const HS_SILPH_CO_5F_ITEM_3            ; A5
	const HS_SILPH_CO_6F_1                 ; A6
	const HS_SILPH_CO_6F_2                 ; A7
	const HS_SILPH_CO_6F_3                 ; A8
	const HS_SILPH_CO_6F_ITEM_1            ; A9
	const HS_SILPH_CO_6F_ITEM_2            ; AA
	const HS_SILPH_CO_7F_1                 ; AB
	const HS_SILPH_CO_7F_2                 ; AC
	const HS_SILPH_CO_7F_3                 ; AD
	const HS_SILPH_CO_7F_4                 ; AE 
	const HS_SILPH_CO_7F_RIVAL             ; AF
	const HS_SILPH_CO_7F_ITEM_1            ; B0 
	const HS_SILPH_CO_7F_ITEM_2            ; B1
	const HS_SILPH_CO_7F_8                 ; B2 XXX sprite doesn't exist
	const HS_SILPH_CO_8F_1                 ; B3
	const HS_SILPH_CO_8F_2                 ; B4
	const HS_SILPH_CO_8F_3                 ; B5
	const HS_SILPH_CO_9F_1                 ; B6
	const HS_SILPH_CO_9F_2                 ; B7 
	const HS_SILPH_CO_9F_3                 ; B8
	const HS_SILPH_CO_10F_1                ; B9 
	const HS_SILPH_CO_10F_2                ; BA
	const HS_SILPH_CO_10F_3                ; BB XXX never (de)activated?
	const HS_SILPH_CO_10F_ITEM_1           ; BC
	const HS_SILPH_CO_10F_ITEM_2           ; BD
	const HS_SILPH_CO_10F_ITEM_3           ; BE
	const HS_SILPH_CO_11F_1                ; BF 
	const HS_SILPH_CO_11F_JAMES            ; C0
	const HS_SILPH_CO_11F_2                ; C1 
	const HS_SILPH_CO_11F_JESSIE           ; C2
	const HS_UNUSED_MAP_F4_1               ; C3 XXX sprite doesn't exist
	const HS_POKEMON_MANSION_2F_ITEM       ; C4
	const HS_POKEMON_MANSION_3F_ITEM_1     ; C5
	const HS_POKEMON_MANSION_3F_ITEM_2     ; C6
	const HS_POKEMON_MANSION_B1F_ITEM_1    ; C7
	const HS_POKEMON_MANSION_B1F_ITEM_2    ; C8
	const HS_POKEMON_MANSION_B1F_ITEM_3    ; C9
	const HS_POKEMON_MANSION_B1F_ITEM_4    ; CA
	const HS_POKEMON_MANSION_B1F_ITEM_5    ; CB
	const HS_SAFARI_ZONE_EAST_ITEM_1       ; CC
	const HS_SAFARI_ZONE_EAST_ITEM_2       ; CD
	const HS_SAFARI_ZONE_EAST_ITEM_3       ; CE
	const HS_SAFARI_ZONE_EAST_ITEM_4       ; CF
	const HS_SAFARI_ZONE_NORTH_ITEM_1      ; D0
	const HS_SAFARI_ZONE_NORTH_ITEM_2      ; D1
	const HS_SAFARI_ZONE_WEST_ITEM_1       ; D2
	const HS_SAFARI_ZONE_WEST_ITEM_2       ; D3
	const HS_SAFARI_ZONE_WEST_ITEM_3       ; D4
	const HS_SAFARI_ZONE_WEST_ITEM_4       ; D5
	const HS_SAFARI_ZONE_CENTER_ITEM       ; D6
	const HS_CERULEAN_CAVE_2F_ITEM_1       ; D7
	const HS_CERULEAN_CAVE_2F_ITEM_2       ; D8
	const HS_CERULEAN_CAVE_2F_ITEM_3       ; D9
	const HS_CERULEAN_CAVE_2F_ITEM_4       ; DA
	const HS_MEWTWO                        ; DB
	const HS_CERULEAN_CAVE_B1F_ITEM_1      ; DC
	const HS_CERULEAN_CAVE_B1F_ITEM_2      ; DD
	const HS_CERULEAN_CAVE_B1F_ITEM_3      ; DE
	const HS_CERULEAN_CAVE_B1F_ITEM_4      ; DF
	const HS_VICTORY_ROAD_1F_ITEM_1        ; E0
	const HS_VICTORY_ROAD_1F_ITEM_2        ; E1
	const HS_WAY_OF_FISH_1F_SISTER1
	const HS_WAY_OF_FISH_1F_SISTER2
	const HS_WAY_OF_FISH_BF_ARROKUDA	   ; E2
	const HS_SAFFRON_SHADY_HOUSE_GUY1	   ; E3
	const HS_SAFFRON_SHADY_HOUSE_GUY2	   ; E4
	const HS_SAFFRON_SHADY_HOUSE_GUY3	   ; E5
	const HS_SAFFRON_SHADY_HOUSE_GUY4	   ; E6
	const HS_CHAMPIONS_ROOM_OAK            ; E7
	const HS_SEAFOAM_ISLANDS_1F_BOULDER_1  ; E8
	const HS_SEAFOAM_ISLANDS_1F_BOULDER_2  ; E9
	const HS_SEAFOAM_ISLANDS_B1F_BOULDER_1 ; EA
	const HS_SEAFOAM_ISLANDS_B1F_BOULDER_2 ; EB
	const HS_SEAFOAM_ISLANDS_B2F_BOULDER_1 ; EC
	const HS_SEAFOAM_ISLANDS_B2F_BOULDER_2 ; ED
	const HS_SEAFOAM_ISLANDS_B3F_BOULDER_1 ; EE
	const HS_SEAFOAM_ISLANDS_B3F_BOULDER_2 ; EF
	const HS_SEAFOAM_ISLANDS_B3F_BOULDER_3 ; F0
	const HS_SEAFOAM_ISLANDS_B3F_BOULDER_4 ; F1
	const HS_SEAFOAM_ISLANDS_B4F_BOULDER_1 ; F2     
	const HS_SEAFOAM_ISLANDS_B4F_BOULDER_2 ; F3           
	const HS_ARTICUNO                 	   ; F4      
	const HS_DAISY_SITTING_COPY            ; F5
	const HS_DAISY_WALKING_COPY            ; F6
	const HS_TOWN_MAP_COPY                 ; F7
	DEF NUM_HS_OBJECTS EQU const_value
